### ISSUE TITLE
Sponsorship Update

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#22]
We are at a small number of official sponsors right now which makes the current carousel look a bit wonky. Implement a temporary solution (such as just listing the two images next to each other with their respective links).

**Comment by CooperW824** [comment]
The way the sponsorship carousel and sponsors.json is setup now is that the sponsors are split into 'sponsor groups' which are groups of anywhere from 1-4 sponsors, if you reduce the amount of sponsors in one group in `sponsors.json` we can reduce it to fewer sponsors per page.

**Comment by maryellenmarino** [comment]
Note: Samantha is working with Justin on this task in a pair
