### ISSUE TITLE
Sponsorship Carousel V2

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#23]
As the final sponsorship design, we want a multi-window automatic scrolling carousel. This would appear with multiple images at one time appearing to seamlessly go off screen and then re-appear on the other side. It should be smooth. 

This library has potential: https://github.com/YIZHUANG/react-multi-carousel but hasn't been updated in a while, so it might be best to use regular bootstrap.

This ticket is meant for developers with a little bit of ITWS background.

Also - please split this into multiple commits when working! This will be slightly on the longer side.

**Comment by RavenLLevitt** [comment]
If you have any questions about the design reach out to confirm before you start working on it to prevent wasted dev time.

**Comment by maryellenmarino** [comment]
Note that the sponsorship design was updated by the Technology team and this issue can be closed.
