### ISSUE TITLE
Sponsorship Packet

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#24]
We currently have a sponsorship packet that is not being linked or displayed on the website. We want to encourage people that view our website to sponsor. 

**Design Portion**: Figure out how to best display a sponsorship packet. Do we want to link it somewhere, can we somehow embed the pdf into the webpage, etc. Document any designing you can so that the design portion counts towards your RCOS contributions.

**Coding Portion**: Confirm design choice with Mel and implement it.

**Comment by CooperW824** [comment]
Added in PR #52
