### ISSUE TITLE
Website Page Refactoring

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#25]
We are starting to add a lot more content to the website, and right now the pages all scroll downwards. It may be better to have these clickable at the top and navigate to a separate page. A menu dropdown or something could also be good. Look into the design part of this, create a branch, and start implementing switches for the page routing. 

Create a PR once you've made significant progress with a thorough description and some screenshots of what the changes mean. We can determine next steps from there.

**Comment by CooperW824** [comment]
React router for page routing: [https://reactrouter.com/en/main](https://reactrouter.com/en/main) 
(Note I have not used this library before, most of my experience is with NextJS' router, but this looks promising.)
