### ISSUE TITLE
Schedule Page (2 people)

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#29]
The event is coming up soon! We need an interactive schedule page to show what is going on and when. Contact Mel to get the full schedule to use for this.

**Design**: First, design what the page will look like. We want there to be highlighting over the current event when it is actually going on. Make sure the design aligns with overall site theme and make it look nice!

**Coding**: Title and code the full schedule. You will probably want to make and design the schedule component first and then put it on the page you created.

Make sure to use responsive design!! This needs to look good on mobile too. There are many videos on how to do this, so make sure to look into things like bootstrap first, as well as just responsive design in general.

This will need to be split into multiple commits. Make sure to not add it all into one as this is a bigger project!!

**Comment by CooperW824** [comment]
Finished in #101
