### ISSUE TITLE
Prizes page (2 people)

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#30]
Let's be honest - most people come for the prizes 😆 

We expect a lot of people to be viewing this page, so let's make it look good! First, design what the page will look like.

Content: Include all prize categories, as well as a description about the prize category. We want to make sure we mention what is won as well. On the page overall, make sure to include something along the lines of: $5k+ (for now) to catch people's eye.

**Comment by CooperW824** [comment]
Finished with #71
