### ISSUE TITLE
[BUG] Description Typo Fix

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#34]
![Image](https://user-images.githubusercontent.com/74571866/269056860-a69af34d-8e63-45dd-9e1a-a4ab71cbf2d3.png)

There is a bug in the description that says 'inspring' instead of 'inspiring`. Fix that.

**Comment by Jordan231111** [comment]
ok.

**Comment by maryellenmarino** [comment]
@d-nieto246 What is the status on this?

**Comment by maryellenmarino** [comment]
It should just need 1 letter change, a commit, and then a PR out. I can merge as soon as that's completed.

**Comment by CooperW824** [comment]
Fixed in #65
