### ISSUE TITLE
Adding Direct Donation Link

### ISSUE THREAD

**Issue by RavenLLevitt** [hack-rpi/HackRPI-Website2023#64]
Add this link as a button below the Alumni Donation Booklet on the sponsorship page for easier access to donations. Use the design language established within the website to make the button look like the image below but replace the text with "Donate".

Link: https://tinyurl.com/hackrpi-donation

<img width="184" alt="image" src="https://github.com/hack-rpi/HackRPI-Website2023/assets/103865865/da7b5040-8f4d-40dd-9ef2-169a818ca473">

**Comment by CooperW824** [comment]
Added in #95
