### ISSUE TITLE
Prize page gears

### ISSUE THREAD

**Issue by maryellenmarino** [hack-rpi/HackRPI-Website2023#79]
The gears on the prize page look great, but are kind of difficult to see being black on black. Replace this with something that is more of a dark grey in-line with our theme. 

You may need to find an additional image of the same style, or just do some image editing to get it to look the way we're looking for. The actual design of the gear should not change. 
![image](https://github.com/hack-rpi/HackRPI-Website2023/assets/74571866/5f5baa07-4ae1-4361-b2c0-4bf1d3a6175d)

**Comment by CooperW824** [comment]
Fixed in #84
